
export const metadata = {
    title: 'Погода',
    // description: 'Generated by create next app',
  }

export default function DashboardLayout({
    children,
}:{children: React.ReactNode;
}){
    return <>
        {children}
        </>
}